In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import random

##  표준화 (Standardization)

### (1) Numpy 를 이용한 표준화 

In [5]:
data = np.random.randint(1000, size=(3, 4))
print('raw_data:\n', data)


data_stand_np = (data - np.mean(data, axis = 0)) /np.std(data, axis=0)
print('numpy standardized data: \n', data_stand_np)

raw_data:
 [[231 183 852 513]
 [810 223 122 974]
 [993 992 671 220]]
numpy standardized data: 
 [[-1.3762905  -0.76014687  0.97834786 -0.18043812]
 [ 0.40642135 -0.65270561 -1.37355315  1.30495424]
 [ 0.96986914  1.41285248  0.39520528 -1.12451612]]


### (2) scipy.stats 를 이용한 표준화 : zscore( )

In [7]:
import scipy.stats as ss

In [8]:
data_stand_ss = ss.zscore(data)

print('scipy standardized data: \n', data_stand_ss)

scipy standardized data: 
 [[-1.3762905  -0.76014687  0.97834786 -0.18043812]
 [ 0.40642135 -0.65270561 -1.37355315  1.30495424]
 [ 0.96986914  1.41285248  0.39520528 -1.12451612]]


### (3) sklearn.preprocessing 을 이용한 표준화 

In [12]:
# standardScaler().fit_transform()

from sklearn.preprocessing import StandardScaler

data_stand_skl = StandardScaler().fit_transform(data)
print('sklearn standardized data: \n', data_stand_skl)

sklearn standardized data: 
 [[-1.3762905  -0.76014687  0.97834786 -0.18043812]
 [ 0.40642135 -0.65270561 -1.37355315  1.30495424]
 [ 0.96986914  1.41285248  0.39520528 -1.12451612]]


## 정규화 (Normalization)

### (1) Numpy를 이용한 정규화 
#### Z- ( X - min( ) / (max( ) - min ( ) ) 

In [14]:
data_minmax_np = (data -np.min(data, axis = 0)) / (np.max(data, axis=0) - np.min(data, axis = 0))
print('numpy minmax data: \n', data_minmax_np)

numpy minmax data: 
 [[0.         0.         1.         0.38859416]
 [0.75984252 0.04944376 0.         1.        ]
 [1.         1.         0.75205479 0.        ]]


In [15]:
data

array([[231, 183, 852, 513],
       [810, 223, 122, 974],
       [993, 992, 671, 220]])

In [16]:
np.min(data)

122

### (3) sklearn.preprocessing 을 이용한 정규화

In [19]:
# MinMaxScaler().fit_transform()
from sklearn.preprocessing import StandardScaler
data_minmax_skl = MinMaxScaler().fit_transform(data)
print('sklearn mixmax data: \n', data_mixmax_skl)

NameError: name 'MinMaxScaler' is not defined