## 행렬( Matrix ): 선형대수 (Linear Algebra)

In [1]:
import numpy as np

### 행렬 (내적 곱셈 ,dot product ) 연산

In [19]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

print(A)  # (2,3)
print(B)  # (3,2)

dot_product = np.dot(A, B)
print(dot_product)

# A*B shape 이 맞지 않아 오류 발생  / elementwise 요소간의 곱셈( 1:1 ) mapping 되어야 한다.

2 

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


2

# (2, 3) * (3, 2) = (2, 2)

# (m, n) * (n, l) = (m , l)     !!  필수 암기 요망 !! 

# (10, 4) * (x, y) = (10 2)     x= 4 , y= 2

### Matrix (내적 곱셈) 연산

In [20]:
A = np.mat("1, 2, 3;4, 5, 6")
B = np.mat("7, 8;9, 10;11, 12")

print(A)
print(B)
print(type(A))  # <class 'numpy.matrix'>
print(A*B)      # dot(내적 곱셈) 연산 

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
<class 'numpy.matrix'>
[[ 58  64]
 [139 154]]


### 역행렬 구하기 (Inverse) 

In [21]:
A = np.mat("2 4 6;4 2 6;10 -4 18")
print(type(A))
print(A)

inverse = np.linalg.inv(A)  # A의 역행렬 반환 

print(inverse)
print(A*inverse)  # 행렬 A *  A의 역행렬 => 항등(단위) 행렬 (대각선으로는 1이고 나머지는 0인 행렬, '0' 행렬)
print(A*inverse - np.eye(3))  # 항등행렬 - 항등행렬   =  요소가 모두 0이 된다. 값  ,  00000000

np.eye(3)

<class 'numpy.matrix'>
[[ 2  4  6]
 [ 4  2  6]
 [10 -4 18]]
[[-0.41666667  0.66666667 -0.08333333]
 [ 0.08333333  0.16666667 -0.08333333]
 [ 0.25       -0.33333333  0.08333333]]
[[ 1.00000000e+00  1.11022302e-16 -2.77555756e-17]
 [-2.22044605e-16  1.00000000e+00 -2.77555756e-17]
 [-8.88178420e-16  1.22124533e-15  1.00000000e+00]]
[[-1.11022302e-16  1.11022302e-16 -2.77555756e-17]
 [-2.22044605e-16  4.44089210e-16 -2.77555756e-17]
 [-8.88178420e-16  1.22124533e-15 -2.22044605e-16]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 선형 방정식 풀이  : 선형 시스템을 해석 

In [22]:
C= np.mat("1 -2 1;0 2 -8;-4 5 9")
print("C:", C)
b = np.array([0,8,-9])
print("b:", b)

# 미지수가 3개인 연립방정식 
# 1 * x0 - 2* x1 + 1 * x2 = 0 
# 0 * x0 + 2* x1 - 8 * x2 = 8 
# -4* x0 + 5* x1 + 9 * x2 = -9

C: [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
b: [ 0  8 -9]


In [23]:
x = np.linalg.solve(C, b)
print('Solution:', x)
print("Check:\n", np.dot(C, x))  # 행렬의 곲셈

# A dot x = b 

Solution: [29. 16.  3.]
Check:
 [[ 0.  8. -9.]]


### 역행렬을 사용해 연립방정식 답을 구하기 

In [28]:
# A dot x => b

# x = A의 역행렬 * b

inverse = np.linalg.inv(C)
print(inverse)
x = np.dot(inverse, b)
print(x)

[[29.  11.5  7. ]
 [16.   6.5  4. ]
 [ 4.   1.5  1. ]]
[[29. 16.  3.]]


### 기타 연산자 : zero( ), ones( )


In [29]:
zero_data = np.zeros(10)
print(zero_data)

zero_data = np.zeros((3, 4))
print(zero_data)

one_data = np.ones(10)
print(one_data)

one_data = np.ones((3, 4))
print(one_data)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 난수 발생 함수  - 초기 학습 시킬때 데이터를 램덤하게 정렬
####   rand( ) :   실수 /  randint( ) : 정수 /  randn( ) : 정규분표 

### 실수  : rand( )

In [35]:
np.random.seed(5)
print(np.random.rand(3, 4))    # 값의 범위 : 0 ~ 1사이  , shape ; (3, 4)

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]
 [0.2968005  0.18772123 0.08074127 0.7384403 ]]


### 정수 :  randint( ) 

In [32]:
print(np.random.randint(10, size = (3,4)))    # 값의 범위 : 0 ~ 9사이  , shape ; (3, 4)

[[1 5 8 8]
 [9 9 7 3]
 [9 8 9 1]]


### 정규 분포 : randn( ) 

In [33]:
print(np.random.randn(10, 10))    # 값의 범위 : 10 ~ 10 사이의   

[[-0.60688084 -0.09407775  0.3243757  -0.55928514  0.2319852  -0.14302166
  -0.3510375   0.94976068  0.13391899 -1.07904061]
 [ 0.47565867 -0.81627478 -0.74401177 -0.34760534 -0.18892292 -0.23634343
  -1.02606922 -1.07282697 -0.503377   -1.64607861]
 [ 0.22413082 -1.75939548  1.04662263 -1.04627072  0.24968939  1.16650763
  -0.28950106  0.39929331 -0.68546174 -0.17616388]
 [ 1.6112514  -0.25616277  0.62451355  0.15856173  1.56094421 -0.10885557
   0.54656463 -1.64486166 -0.52639809  0.98445294]
 [-0.1350921  -0.33499264 -0.21509738 -0.30214144  2.07041213  0.74491202
  -0.05301779  2.37161849  0.32958327 -1.18168699]
 [ 0.23483945  0.05451016 -0.38655455 -0.11869647 -0.41186548  0.26123948
   1.73511966 -1.96582999 -0.40964458  0.12491264]
 [ 1.96278955 -0.12291272  0.85256869  0.66400168  0.15668337 -0.09937392
  -1.80169085  0.63181758  2.02161863 -1.4884013 ]
 [-0.12000564  0.4304067  -0.51603718 -1.15755154 -1.15887731  1.50139796
  -0.11579614  0.73331057 -1.17764195 -0.55689604]


In [34]:
# Hx = X * W 
np.random.seed(100)
